// LOCALHOST 
###  Get all contacts 
GET http://localhost:8080/ HTTP/1.1

###Get contact by id
GET http://localhost:8080/contacts
### 
GET http://localhost:8080/contacts/640379deb0260175abea6db1
### 
GET http://localhost:8080/contacts/640379deb0260175abea6db2
###
GET http://localhost:8080/contacts/640379deb0260175abea6db3

### Create contact 
POST http://localhost:8080/contacts HTTP/1.1 content-type: application/json

{ 
"firstName": "Albus", "lastName": "Dumbledore", "email": "foreverFenix@test.com", "favoriteColor": "Brown", "birthday": "07/19/1881"
}

### PUT contact 
PUT http://localhost:8080/contacts/640379deb0260175abea6db3 HTTP/1.1 content-type: application/json

{
"firstName":"Severus", "lastName":"snape", "email":"snake@gmail.com", "favoriteColor":"Green", "birthday":"01/09/1960"
} 

### DELETE contact 
DELETE http://localhost:8080/contacts/6407bee0d2a48aec3183acd4 HTTP/1.1
