// LOCALHOST   
###  Get all products 
GET http://localhost:8080/ HTTP/1.1

### Get products by id
GET http://localhost:8080/products

### Get kits by id
GET http://localhost:8080/kit
### 
GET http://localhost:8080/products/Ibuprofen
### 
GET http://localhost:8080/kit/One-Person
###
GET http://localhost:8080/products/641d20dbb2f7f6e188cfe2ee

### Create products 
POST http://localhost:8080/products HTTP/1.1
content-type:application/json

{
    "Name": "Gel",
    "Price": 7.77,
    "Type": "Fluid",
    "Count": "16 Fl Oz",
    "Description": " Alcohol Antiseptic 80% Topical Solution Hand Sanitizer",
    "Category": "Medicine"
}

### Create kits 
POST http://localhost:8080/kit
content-type:application/json

{
    "NameKit": "Four-Person",
    "Content":[
      {
				"product1": "Paracetamol x 2u",
				"product2": "Ibuprofen x 2u",
				"product3": "Bandages Medical x 4u",
				"product4": "Isopropyl Alcohol 70% x 1u",
				"product5": "Diclofenac Gel 1% x 2u",
				"product6": "KN95 Face Masks x 2u",
				"product7": "Adhesive Tape Medical x 2u",
				"product8": "Canned tuna in oil x 4u",
				"product9": "Cookies x 4u",
				"product10": "Chocolates x 4u",
				"product11": "Legumes x 4u",
				"product12": "Warm Clothing x 4u",
				"product13": "Blankets x 4u",
				"product14": "Hat and Gloves Set x 4u",
				"product15": "Water bottles x 4u",
				"product16": "Battery Operated Radio x 1u",
				"product17": "Portable Charger x 2u",
				"product18": "Lanterns x 2u",
				"product19": "Wet Toilet Wipes x 2u",
				"product20": "Toilet Paper x 4u",
				"product21": "Backpack x 4u"
        }
      ],
    "TotalPrice": 2538.75
}

### PUT 
PUT http://localhost:8080/products/Gel HTTP/1.1
content-type: application/json

{
    "Name": "GelFluid",
    "Price": 3.77,
    "Type": "Fluid",
    "Count": "8 Fl Oz",
    "Description": " Alcohol Antiseptic 80% Topical Solution Hand Sanitizer",
    "Category": "Medicine"
}

### DELETE 
DELETE http://localhost:8080/products/GelFluid HTTP/1.1

### DELETE 
DELETE http://localhost:8080/kit/Four-Person HTTP/1.1
