// LOCALHOST 
### 
GET http://localhost:8080/ HTTP/1.1
###
GET http://localhost:8080/contacts
### 
GET http://localhost:8080/contacts/640379deb0260175abea6db1
### 
GET http://localhost:8080/contacts/640379deb0260175abea6db2
###
GET http://localhost:8080/contacts/640379deb0260175abea6db3

